namespace Surl.Cli;

/// <summary>
/// What <c>surl --manual</c> writes (ADR-0034 decision 6): the long text, section by section,
/// every line within 79 columns and none with trailing spaces. Each statement is true of the
/// code it describes; work that changes that code updates the section in the same change.
/// </summary>
public static class ManualText
{
    private static readonly string[] Lines =
    [
        "NAME",
        "",
        "    surl - the server-side mate of curl",
        "",
        "SYNOPSIS",
        "",
        "    surl [options] <url>...",
        "",
        "DESCRIPTION",
        "",
        "    surl is the server-side mate of curl: for each request upstream curl makes,",
        "    surl is the server that answers it. Where curl [options] <url> names what",
        "    to fetch, surl [options] <url> names what to listen on. surl --version",
        "    names the schemes this build serves.",
        "",
        "    Options and listen URLs may come in any order and are read left to right;",
        "    the first error ends the reading, and nothing is served. After -- every",
        "    argument is a listen URL.",
        "",
        "LISTEN URLS",
        "",
        "    A listen URL is scheme://host[:port][/]. The host is an IPv4 address, an",
        "    IPv6 address in brackets, or a host name; 0.0.0.0 and [::] listen on every",
        "    interface, and nothing else does. Without a port the scheme's default port",
        "    is used, and port 0 asks for an ephemeral port. A listen URL has no user",
        "    name, password, path, query or fragment.",
        "",
        "    Once every listener has bound, surl writes one line per listen URL to",
        "    stdout, in command-line order:",
        "",
        "        Listening on <scheme>://<host>:<bound port>/",
        "",
        "    The line shows the port each listener got, so a test that asked for port 0",
        "    reads its port from it. Several listen URLs are several listeners; tftp",
        "    listens on UDP and every other scheme on TCP.",
        "",
        "DEPLOYMENT CHECKLIST",
        "",
        "    Before running surl where others can reach it:",
        "",
        "    1. Bind a specific address rather than 0.0.0.0 or [::], unless every",
        "       interface should answer.",
        "    2. Give --directory for files and state that must survive a restart.",
        "    3. Give --cert and --key for secure schemes, never --self-signed.",
        "    4. Configure accounts with --user-file rather than --user, which other",
        "       local users can read in the process list, and let only the user surl",
        "       runs as read the file.",
        "    5. Leave --allow-uploads, --list-directories, --follow-symlinks and",
        "       --serve-dot-files off unless they are needed.",
        "    6. Review the limits (see LIMITS).",
        "    7. Start with no loosening option, and treat any \"surl: warning:\" line at",
        "       start as one left on.",
        "    8. Pick a log level and a --log-file.",
        "    9. Stop surl with Ctrl+C or SIGTERM; it exits 0.",
        "",
        "DATA DIRECTORY",
        "",
        "    --directory <path> serves the files under <path> and keeps service state",
        "    under <path>/.surl/. The .surl folder is never served, even with",
        "    --serve-dot-files: a read of it is answered as a missing entry, a listing",
        "    leaves it out, and an upload into it is refused.",
        "",
        "    While it runs, surl holds a lock on <path>/.surl/lock, so one surl at a",
        "    time serves a data directory; a second one started on it exits 124. The",
        "    lock file stays at exit, and the operating system releases the lock when",
        "    surl ends, even when it is killed.",
        "",
        "    A path that is missing, not a directory or unreadable exits 37; surl does",
        "    not create it. A .surl folder or lock file that cannot be created exits 23,",
        "    so a read-only directory cannot be served.",
        "",
        "    The MQTT server keeps its retained messages in",
        "    <path>/.surl/mqtt/retained-messages and loads them at start; a file that",
        "    cannot be read or does not parse exits 37.",
        "",
        "IN-MEMORY MODE",
        "",
        "    Without --directory, surl serves an in-memory file system. It starts empty,",
        "    holds at most 256 MiB, touches no disk, and is lost at exit. Uploads into",
        "    it still need --allow-uploads.",
        "",
        "ACCOUNTS",
        "",
        "    -u, --user <user:password> adds one account, and may be given again to add",
        "    more. The value is split at its first colon, so a user name never holds",
        "    one. An empty user name makes the password a Bearer token.",
        "",
        "    --user-file <file> reads accounts from a file, after every --user account.",
        "    The file is UTF-8 (a byte-order mark is skipped), with LF or CR LF line",
        "    ends; each line is one user:password, read as --user reads its value, and",
        "    blank lines and lines starting with # are skipped. The passwords are in",
        "    clear, so let only the user surl runs as read the file. A file that cannot",
        "    be read exits 37, and a malformed line exits 2, naming the line.",
        "",
        "    Unless --allow-anonymous is given: with no account configured, an HTTP GET",
        "    or HEAD needs no login, and every login is refused; once any account is",
        "    configured, every HTTP request needs a login; any other HTTP method, and",
        "    every MQTT CONNECT, always needs one.",
        "",
        "    --auth <methods> sets the methods accepted and offered, comma-separated,",
        "    in any case. For HTTP: negotiate, ntlm, digest, basic, bearer and",
        "    aws-sigv4. For SMTP, IMAP and POP3 logins, each SASL mechanism by its",
        "    name in lower case, as curl's login option AUTH=<mech> names it: ntlm,",
        "    digest-md5, cram-md5, plain, login, oauthbearer and xoauth2, and apop for",
        "    POP3's APOP; this build serves none of those three protocols yet. Without",
        "    it they are digest, cram-md5, basic, plain, login, bearer, oauthbearer,",
        "    xoauth2 and aws-sigv4. gssapi and external are read, but a start that",
        "    gives either writes \"surl: (2) --auth <word> is not available in this",
        "    build\" and exits 2.",
        "",
        "SSH OPTIONS",
        "",
        "    --hostkey <file> names one SSH host private key, and may be given again to",
        "    add more. --hostcert <file> names one OpenSSH host certificate for such a",
        "    key, and may be given again. --throwaway-hostkey asks for a throwaway RSA",
        "    host key instead, and cannot be used with --hostkey. --pass <phrase>",
        "    decrypts a --hostkey key as it does a --key.",
        "",
        "    --authorized-keys <user:file> names the OpenSSH authorized_keys file whose",
        "    public keys <user> may log in with, and may be given again for other",
        "    users. The value is split at its first colon, so a Windows path after it",
        "    keeps its drive colon; a user given twice is refused.",
        "",
        "    --allow-weak-ssh-algorithms also offers SSH algorithms built on SHA-1, MD5,",
        "    CBC, RC4, 3DES and 1024-bit Diffie-Hellman.",
        "",
        "    This build has no SSH server yet: these options are read and checked, and",
        "    a start that gives --hostkey, --hostcert, --throwaway-hostkey,",
        "    --authorized-keys or --allow-weak-ssh-algorithms writes \"surl: (2)",
        "    --<option> is not available in this build\" and exits 2.",
        "",
        "LOOSENING OPTIONS",
        "",
        "    --allow-anonymous, --allow-plaintext-auth, --auth and --self-signed each",
        "    loosen a secure default for tests, and each writes a \"surl: warning:\" line",
        "    on start (--self-signed only when it makes its certificate).",
        "    --throwaway-hostkey is one too, refused by this build (see SSH OPTIONS).",
        "    What each one loosens, and why none is the default, is written by:",
        "",
        "        surl --help testing",
        "",
        "LOG LEVELS",
        "",
        "    surl has five log levels, each writing what the one before it writes and",
        "    more:",
        "",
        "    - none (-s): nothing, not even the Listening on lines or the failure",
        "      messages; the exit code still says what failed.",
        "    - error (-s -S): the \"surl: (N)\" failure messages on stderr, and a note",
        "      when a protocol server fails.",
        "    - info (the default): the Listening on lines, the startup warnings and one",
        "      line per exchange.",
        "    - verbose (-v): a line for every exchange event.",
        "    - trace (--trace <file>, --trace-ascii <file>): a dump of every byte to",
        "      <file>, or to stdout for -; --trace-ascii leaves out the hex.",
        "",
        "    --log-level <level> sets a level by its name. The last level option given",
        "    wins, and -S is applied after the whole command line is read. --trace-time",
        "    stamps each exchange log line with the time.",
        "",
        "    The log goes to stderr, or is appended to the file --log-file <file> names",
        "    (- for stdout). The failure messages and command-line errors always go to",
        "    stderr, and the help, the manual and the version are written at every",
        "    level. A log or trace file that cannot be opened exits 23, and so does a",
        "    trace file that is the --log-file file.",
        "",
        "LIMITS",
        "",
        "    Each limit is 0 for no limit:",
        "",
        "    - --max-connections <number>: connections at once, all listeners together;",
        "      default 1024.",
        "    - --max-connections-per-address <number>: connections at once from one",
        "      address; default 100.",
        "    - --idle-timeout <seconds>: an exchange idle this long is closed; default",
        "      120.",
        "    - -m, --max-time <seconds>: the longest one exchange may take; default",
        "      3600.",
        "    - --head-timeout <seconds>: the time a client has to send a request head,",
        "      command line or first packet; default 30.",
        "    - --max-request-head <bytes>: the largest HTTP request head; default 100k.",
        "    - --max-line <bytes>: the longest command line; default 8192.",
        "    - --max-message <bytes>: the largest framed message, such as an MQTT",
        "      packet; default 1M.",
        "    - --max-filesize <bytes>: the largest upload; default 100M.",
        "",
        "    A size may end in k, M, G, T or P, each 1024 times the one before. A limit",
        "    reached ends only the connection or exchange that reached it, answered in",
        "    its protocol's own words where it has them; it never ends surl.",
        "",
        "EXIT CODES",
        "",
        "    - 0: help, an --aihelp answer, the manual or the version was written, or",
        "      surl was stopped by Ctrl+C or SIGTERM.",
        "    - 1: a listen URL names a scheme this build does not serve.",
        "    - 2: the command line cannot be used: an option refused or not available",
        "      in this build, a malformed --user-file, or a --cacert file that does not",
        "      exist.",
        "    - 3: a listen URL is malformed.",
        "    - 6: a listen URL names a host that resolves to nothing.",
        "    - 23: the .surl folder or its lock file cannot be created, a log or trace",
        "      file cannot be opened, or the trace file is the --log-file file.",
        "    - 37: the data directory cannot be opened, or the --user-file or the MQTT",
        "      retained-message file cannot be read.",
        "    - 45: a listener cannot bind its address and port.",
        "    - 58: a secure listen URL has no certificate, or the --cert or --key file",
        "      cannot be used.",
        "    - 77: the --cacert file cannot be read.",
        "    - 124: another surl holds the data directory.",
        "    - 125: surl failed while serving.",
        "",
        "SEE ALSO",
        "",
        "    surl --help all, surl --help category, surl --aihelp, curl(1),",
        "    https://github.com/StewartScottRogers/Surl",
    ];

    /// <summary>The whole manual, each line followed by <see cref="Environment.NewLine"/>.</summary>
    public static string Text { get; } = string.Concat(Lines.Select(line => line + Environment.NewLine));
}
