<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <InternalsVisibleTo Include="Surl.Cryptography.BcryptPbkdf.UnitTests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Surl.Cryptography.Blowfish.UnitLibrary\Surl.Cryptography.Blowfish.UnitLibrary.csproj" />
  </ItemGroup>

</Project>
