<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <InternalsVisibleTo Include="Surl.Protocol.Gopher.UnitTests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Surl.Protocol.Abstractions.UnitLibrary\Surl.Protocol.Abstractions.UnitLibrary.csproj" />
    <ProjectReference Include="..\Surl.Content.UnitLibrary\Surl.Content.UnitLibrary.csproj" />
  </ItemGroup>

</Project>
