<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <InternalsVisibleTo Include="Surl.Authentication.UnitTests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Surl.Cryptography.UnitLibrary\Surl.Cryptography.UnitLibrary.csproj" />
    <ProjectReference Include="..\Surl.Kerberos.UnitLibrary\Surl.Kerberos.UnitLibrary.csproj" />
    <ProjectReference Include="..\Surl.Protocol.Abstractions.UnitLibrary\Surl.Protocol.Abstractions.UnitLibrary.csproj" />
  </ItemGroup>

</Project>
