<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <InternalsVisibleTo Include="Surl.Protocol.Imap.UnitTests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Surl.LineProtocol.UnitLibrary\Surl.LineProtocol.UnitLibrary.csproj" />
    <ProjectReference Include="..\Surl.MailStore.UnitLibrary\Surl.MailStore.UnitLibrary.csproj" />
    <ProjectReference Include="..\Surl.Protocol.Abstractions.UnitLibrary\Surl.Protocol.Abstractions.UnitLibrary.csproj" />
  </ItemGroup>

</Project>
