using System.Text;

namespace Surl.Cryptography.BcryptPbkdf;

/// <summary>
/// Pins <see cref="BcryptPbkdf" /> to the vectors "generated by the reference
/// implementation from OpenBSD" in Go's
/// https://github.com/golang/crypto/blob/master/ssh/internal/bcrypt_pbkdf/bcrypt_pbkdf_test.go
/// (<c>golden</c> and <c>TestBcryptHash</c>), and checks the inputs OpenBSD's
/// <c>bcrypt_pbkdf</c> refuses are an <see cref="ArgumentException" /> (ADR-0051).
/// </summary>
[TestClass]
public sealed class BcryptPbkdfTests
{
    // Go bcrypt_pbkdf_test.go, golden[0]: 12 rounds, a 32-byte key.
    [TestMethod]
    public void DeriveKey_GoGoldenVector0_GivesThePublishedKey()
    {
        AssertDerives(
            "password"u8.ToArray(),
            "salt"u8.ToArray(),
            12,
            "1ae42c05d487bc02f64921a4ebe4ea93bcacfe135fda99974c06b7b01fae149a");
    }

    // Go bcrypt_pbkdf_test.go, golden[1]: 3 rounds, embedded NULs, a 32-byte key.
    [TestMethod]
    public void DeriveKey_GoGoldenVector1_GivesThePublishedKey()
    {
        AssertDerives(
            "passwordy\0PASSWORD\0"u8.ToArray(),
            "salty\0SALT\0"u8.ToArray(),
            3,
            "7f310bd3e78c3280c59ce4595211a2928e8d4ec744c1ed2efc9f764e3388e0ad");
    }

    // Go bcrypt_pbkdf_test.go, golden[2] (from http://thread.gmane.org/gmane.os.openbsd.bugs/20542):
    // 8 rounds, UTF-8 password and salt, an 88-byte key interleaved over three blocks.
    [TestMethod]
    public void DeriveKey_GoGoldenVector2_GivesThePublishedKey()
    {
        AssertDerives(
            Encoding.UTF8.GetBytes("секретное слово"),
            Encoding.UTF8.GetBytes("посолить немножко"),
            8,
            "8df43fc6fe131fc47f0c9e39224bd94c70b6fcc8ee8135faddf61156e6cb2733ea765f315a3e1e4afc35bf8687d189254c1e05a6fe80c0617f9183d67260d6a115c6c94e3603e2303fbb43a76a64523ffda686b1d4518543");
    }

    // Go bcrypt_pbkdf_test.go, TestBcryptHash: password bytes 0 to 63, salt bytes 64 to 127.
    [TestMethod]
    public void ComputeHash_GoBcryptHashVector_GivesThePublishedHash()
    {
        byte[] passwordHash = new byte[64];
        byte[] saltHash = new byte[64];
        for (int index = 0; index < 64; index++)
        {
            passwordHash[index] = (byte)index;
            saltHash[index] = (byte)(index + 64);
        }

        byte[] hash = new byte[BcryptPbkdf.HashSize];

        BcryptPbkdf.ComputeHash(new BlowfishState(), passwordHash, saltHash, hash);

        Assert.AreEqual("87904870eef9deddf8e7611a140106e6aaf1a363d9a2c504db356443721eb555", Convert.ToHexStringLower(hash));
    }

    [TestMethod]
    public void DeriveKey_OneRoundMaximumLengthKey_FillsEveryByte()
    {
        byte[] key = new byte[BcryptPbkdf.MaximumKeySize];

        BcryptPbkdf.DeriveKey("password"u8, "salt"u8, 1, key);

        Assert.AreNotEqual(0, key[^1] | key[0] | key[31]);
    }

    [TestMethod]
    [DataRow(0, 4, 32, "password")]
    [DataRow(8, 0, 32, "salt")]
    [DataRow(8, BcryptPbkdf.MaximumSaltSize + 1, 32, "salt")]
    [DataRow(8, 4, 0, "destination")]
    [DataRow(8, 4, BcryptPbkdf.MaximumKeySize + 1, "destination")]
    public void DeriveKey_LengthOpenBsdRefuses_ThrowsArgumentException(int passwordLength, int saltLength, int keyLength, string parameterName)
    {
        ArgumentException exception = Assert.ThrowsExactly<ArgumentException>(
            () => BcryptPbkdf.DeriveKey(new byte[passwordLength], new byte[saltLength], 1, new byte[keyLength]));

        Assert.AreEqual(parameterName, exception.ParamName);
    }

    [TestMethod]
    public void DeriveKey_ZeroRounds_ThrowsArgumentOutOfRangeException()
    {
        ArgumentOutOfRangeException exception = Assert.ThrowsExactly<ArgumentOutOfRangeException>(
            () => BcryptPbkdf.DeriveKey("password"u8, "salt"u8, 0, new byte[32]));

        Assert.AreEqual("rounds", exception.ParamName);
    }

    private static void AssertDerives(byte[] password, byte[] salt, int rounds, string expectedKey)
    {
        byte[] key = new byte[expectedKey.Length / 2];

        BcryptPbkdf.DeriveKey(password, salt, rounds, key);

        Assert.AreEqual(expectedKey, Convert.ToHexStringLower(key));
    }
}
